# Generated by Django 6.0.7 on 2026-07-17 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_integrationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('snapshots_written', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_runs', to='teams.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'provider', '-started_at'], name='collectors__team_id_7b9876_idx')],
            },
        ),
    ]
