# Generated by Django 6.0.7 on 2026-07-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('newrelic', 'New Relic'), ('sonarqube', 'SonarQube'), ('jira', 'Jira'), ('anthropic', 'Anthropic')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('_credentials', models.TextField(blank=True, db_column='credentials', default='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'provider'), name='uniq_team_provider')],
            },
        ),
    ]
