# Generated by Django 6.0.7 on 2026-07-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('dimension', models.CharField(choices=[('utilization', 'Utilization'), ('impact_speed', 'Impact — speed'), ('impact_quality', 'Impact — quality'), ('impact_experience', 'Impact — experience'), ('cost', 'Cost')], max_length=20)),
                ('unit', models.CharField(max_length=30)),
                ('direction', models.CharField(choices=[('higher', 'Higher is better'), ('lower', 'Lower is better')], default='higher', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('paired_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.metricdefinition')),
            ],
        ),
    ]
