# Generated by Django 6.0.7 on 2026-07-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_seed_catalog'),
        ('teams', '0002_integrationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('per_release', 'Per release'), ('quarterly', 'Quarterly')], max_length=15)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('dimensions_hash', models.CharField(editable=False, max_length=64)),
                ('source', models.CharField(choices=[('system', 'System'), ('survey', 'Survey'), ('manual', 'Manual')], default='system', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.metricdefinition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='teams.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'metric', 'period_start'], name='metrics_met_team_id_9e63c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'metric', 'period_start', 'granularity', 'dimensions_hash'), name='uniq_snapshot_period')],
            },
        ),
    ]
