# Generated by Django 6.0.7 on 2026-07-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metricsnapshot'),
        ('teams', '0002_integrationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('values', models.JSONField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'version'), name='uniq_baseline_version')],
            },
        ),
    ]
